name: ABMCBlockLimiter
main: server.alanbecker.net.Limiter
version: 1.0
api-version: 1.20
author: MasterGabeMOD

commands:
  limiterreload:
    description: Reload the configuration of the ABMCBlockLimiter plugin.
    usage: /limiterreload
    permission: limiter.reload

permissions:
  limiter.reload:
    description: Allows reloading the configuration of the ABMCBlockLimiter plugin.
    default: op
  limiter.bypass:
    description: Allows bypassing placement limits set by the ABMCBlockLimiter plugin.
    default: op
